#!/usr/bin/env bash

#
# ruby aliases.
#

# check if rbenv exists
rbenv &> /dev/null

if [ $? -eq 0 ] ; then
  alias bundle='rbenv exec bundle'
fi

alias rebundle='rm -rf vendor/bundle/* ; mkdir -p vendor/bundle ; bundle install'

