#!/usr/bin/env bash

# get all tags sorted by number based on tag type (stable, testing, etc).

gitags(){
  if [ -z $1 ] ; then
    echo 'usage: gitags <tag-type>'
  else
    tagtype="$1"

    cmd_args=""

    if [ `uname -s` = 'Darwin' ] ; then
      cmd_args="g"
    else
      cmd_args="V"
    fi

    git tag | egrep ^$tagtype | sort -$cmd_args | tail -10
  fi
}

