#!/usr/bin/env bash

# get all tags sorted by number based on tag type (stable, testing, etc).

gitags(){
	if [ -z $1 ] ; then
		echo 'usage: gitags <tag-type>'
	else
		tagtype="$1"

		git tag --list $tagtype* --sort=v:refname | tail -10
	fi
}

