#!/usr/bin/env bash

# get all tags sorted by number based on tag type (stable, testing, etc).

gitags(){
  if [ -z $1 ] ; then
    echo 'usage: gitags <tag-type>'
  else
    tagtype="$1"
    git tag | egrep ^$tagtype | sort -V | tail -10
  fi
}

