#!/usr/bin/env bash

#
# Useful aliases for commands.
# 
# Marcelo Correia Pinheiro
#

# bash
alias ls='ls -G --color=auto'
alias ll='ls -lh'
alias la='ls -Ga'
alias lla='ls -lha'
alias duh='du -sh'
alias vim='vi -p'

# ruby
alias ss='script/server webrick'
alias sc='script/console'
alias as='script/autospec'
alias sg='script/generate'
alias sd='script/destroy'
alias sp='script/plugin'
alias scbr='script/cucumber --format pretty'
