#!/usr/bin/env bash

#
# Script loader.
#

export PATH="/usr/local/git/bin:$PATH"

mypath=${BASH_ARGV[0]%/*}

for file in $mypath/bash/* ; do
  source $file
done

for file in $mypath/git/*  ; do
  source $file
done

for file in $mypath/ruby/* ; do
  source $file
done

