#!/usr/bin/env bash

#
# Script loader.
#

mypath=${BASH_ARGV[0]%/*}

for file in $mypath/**/* ; do
	source $file
done

if [ -d $HOME/.config/salizzar ] ; then
	for file in $HOME/.config/salizzar/* ; do
		source $file
	done
fi

