#!/usr/bin/env bash

#
# Script loader.
#

mypath=${BASH_ARGV[0]%/*}

for file in $mypath/**/* ; do
  if [[ "${file}" != *"/installers/"* ]] ; then
    source $file
  fi
done

DEFAULT_DIR=~/.env/default

if [ -d $DEFAULT_DIR ] ; then
  for file in $DEFAULT_DIR/* ; do
    if [ -f $file ] ; then
      source $file
    fi
  done
fi

