#! /usr/bin/env bash

# import certificates
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

# install from website
curl -sSL https://get.rvm.io | bash -s stable

