#! /usr/bin/env bash

if [ `uname -s` = 'Darwin' ] ; then
	status=`boot2docker status`
	if [ $status == 'poweroff' ] || [ $status == 'aborted' ] ; then
		boot2docker up
	fi

	`boot2docker shellinit`
fi

