#!/usr/bin/env bash

#
# Useful aliases for commands.
#

if [ `uname -s` = 'Darwin' ]; then
  alias ls='ls -G'
fi

alias ll='ls -lh'
alias la='ls -a'
alias lla='ls -lha'
alias duh='du -sh'
alias vim='vi -p'

