#!/usr/bin/env bash

#
# formats a json request with python and pygmentize.
#

json_syntax(){
	pygmentize -l json
}

json_ident(){
	python -mjson.tool
}

json_curl(){
	curl -s $* | json_ident | json_syntax
}

