#!/usr/bin/env bash

#
# formats json_content with python and pygmentize.
#

syntax_json(){
  pygmentize -l json $*
}

ident_json(){
  python -mjson.tool $*
}

json_curl(){
  curl -s $* | ident_json | syntax_json
}

