#! /usr/bin/env bash

export TMP_ENV_PATH=/tmp/env
mkdir -p $TMP_ENV_PATH

loadenv() {
	if  [ -d $TMP_ENV_PATH ] && [ ! -z "$1" ] ; then
		source ~/.config/$USER/env/$1
		mkdir -p $TMP_ENV_PATH && touch $TMP_ENV_PATH/$1
	fi
}

unloadenv() {
	for env_var in $(cat ~/.config/$USER/env/$1 | grep export | awk '{ print $2 }' | awk -F '=' '{ print $1 }') ; do
		unset $env_var
	done

	if [ -d $TMP_ENV_PATH ] && [ -f $TMP_ENV_PATH/$1 ] ; then
		rm $TMP_ENV_PATH/$1
	fi
}

if [ -d $TMP_ENV_PATH ]; then
	for env in $(find $TMP_ENV_PATH -type f) ; do
		loadenv $(basename $env)
	done
fi

