#! /usr/bin/env bash

export TMP_ENV_PATH=/tmp/env

loadenv() {
	if  [ ! -z "$1" ] ; then
		source ~/.config/$USER/env/$1
		mkdir -p $TMP_ENV_PATH && touch $TMP_ENV_PATH/$1
	fi
}

unloadenv() {
	if [ -f $TMP_ENV_PATH/$1 ] ; then
		for env_var in $(cat ~/.config/$USER/env/$1 | grep export | awk '{ print $2 }' | awk -F '=' '{ print $1 }') ; do
			unset $env_var
		done

		rm $TMP_ENV_PATH/$1
	fi
}

for env in $(find $TMP_ENV_PATH -type f) ; do
	loadenv $(basename $env)
done

